### ISSUE TITLE
Kerberos KafkaClient issue

### ISSUE THREAD

**Issue by BIGabor** [cloudera/flink-tutorials#28]
Hi,

we have a kerberized, SSL configured Cluster.
"java.lang.IllegalArgumentException: Could not find a 'KafkaClient' entry in the JAAS configuration. System property 'java.security.auth.login.config' is /data3/yarn/nm/usercache/xuser/appcache/application_1623160563820_0414/jaas-1578655284572927100.conf
How could I provide this param? 
yD security.auth.login.config=="""KafkaClient {...
and 
kafka.sasl.jaas.config== "com.sun.security.auth.module.Krb5LoginModule required useTicketCache=true;" \

I already tried. KafkaClient in jaas.config too.

BR,
Gabor

**Comment by BIGabor** [comment]
I forgot to mention, I tried it without the flink -d param.
The FlinkKafkaProducer without semantic is depreciated, please correct that too.

**Comment by Kashish053** [comment]
Hi.

Do you have any update on this issue?

**Comment by mbalassi** [comment]
Hi @BIGabor ! 

Thanks for reporting the issue, I have also seen the ticket you opened for Cloudera internal support. Did you try specifying the keytab and principal as described [here](https://github.com/cloudera/flink-tutorials/tree/1.12-csa1.3.0.0/flink-secure-tutorial#understanding-security-parameters)? Which tutorial are you running?

You should not need to define the `jaas.conf` directly, Flink tries to generate and distribute it for you given that you have provided all these parameters.

**Comment by BIGabor** [comment]
Hi @mbalassi 

This is our config. The SQL Stream Builder works in our cluster, I get the use ticketcache from there (SQl Streams Flink Log).
Could you please join that meeting too? Or we could have a Coffee in Budapest :).
flink run -m yarn-cluster -p 1 \
-yD security.kerberos.login.keytab=temp/my.keytab \
-yD security.kerberos.login.principal=myprincipal@mydomain \
-yD security.kerberos.login.contexts=Client,KafkaClient \
-yD security.kerberos.login.use-ticket-cache=true \
-yD security.ssl.internal.enabled=true \
-yD security.ssl.internal.keystore=/opt/cloudera/security/pki/keystore.jks \
-yD security.ssl.internal.key-password=password \
-yD security.ssl.internal.keystore-password=password \
-yD security.ssl.internal.truststore=/opt/cloudera/security/pki/truststore.jks \
-yD security.ssl.internal.truststore-password=password \
-yt /opt/cloudera/security/pki/keystore.jks \
-yt /opt/cloudera/security/pki/truststore.jks \
-yt temp/ \
flink-secure-tutorial-1.12-csa1.3.0.0-SNAPSHOT.jar \
--kafkaTopic flink \
--hdfsOutput hdfs:///tmp/flink-sec-tutorial \
--kafka.bootstrap.servers kafka01.domain:9093 \
--kafka.security.protocol SASL_SSL \
--kafka.sasl.kerberos.service.name kafka \
--kafka.ssl.truststore.location /opt/cloudera/security/pki/truststore.jks \
--kafka.ssl.truststore.password password

BR,
Gabor

**Comment by mbalassi** [comment]
Hi @BIGabor,

I am not available today, but am open to taking you up on the coffee offer on Monday or Tuesday. Feel free to ping me via `mbalassi kukac cloudera pont com`.

**Comment by Kashish053** [comment]
Hi @mbalassi ,
With this new version of pushed code in the repository.  I am facing an issue with the class flink. data. Message does not exist.
Can you please commit this class too?

![image](https://user-images.githubusercontent.com/44292726/124249130-de02dd00-db23-11eb-97da-2a11420348dc.png)

**Comment by ferenc-csaky** [comment]
Hi @Kashish053,

The `Message` class is an avro generated class, which now is put under `target` dir to generated sources, so you have to `mvn compile` first.
