### ISSUE TITLE
Some part of the code are obsolete with Flink 1.20

### ISSUE THREAD

**Issue by Timelessprod** [cloudera/flink-tutorials#45]
Hello,

The examples are super helpful to complete the official documentation, but I noticed that there are some part of the code which rely on obsolete code regarding Flink 1.20 version. Namely the SinkFunction class for example is flagged as obsolete by my IDE and reported to be deleted on Flink website: https://nightlies.apache.org/flink/flink-docs-stable/api/java/org/apache/flink/streaming/api/functions/sink/SinkFunction.html.

Is it planned to get a code update ? I find very few example of full and tested Flink jobs in 1.20 on the web, and it would be nice if you could do the migration to help us understand how the current version of Flink works. The new Sink class doesn't seem to behave in the same way as SinkFunction so making the migration myself isn't easy to understand.

Thank you.

**Comment by attilakreiner** [comment]
In the latest version https://github.com/cloudera/flink-tutorials/tree/CSA-OPERATOR-1.1.2 we support flink 1.19: https://github.com/cloudera/flink-tutorials/blob/698c70f0af86a8fcc18090a19f1852645ee61d5d/pom.xml#L41

We plan to support the next flink version in the next release. Thank you for pointing it out though, this is useful feedback, definitely something that we will need to check.

**Comment by Timelessprod** [comment]
Perfect thank you !
